### ISSUE TITLE
Doens't seem to connect to the Language Server

### ISSUE THREAD

**Issue by crbelaus** [elixir-tools/elixir-tools.vscode#45]
I've uninstalled the extension, ran `rm -rf ~/.cache/elixir-tools/` to ensure that there is nothing in there, installed the extension again, confirmed the download of the language server binary but VSCode still seems unable to connect to the language server.

<details><summary>I've enabled the `"elixir-tools.nextls.trace.server": "verbose"` setting and this is what I see.</summary>

```
[Trace - 10:10:53] Sending request 'initialize - (0)'.
Params: {
    "processId": 3932,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.81.1"
    },
    "locale": "en",
    "rootPath": "/Users/crbelaus/Developer/hcmex",
    "rootUri": "file:///Users/crbelaus/Developer/hcmex",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "configuration": true,
            "didChangeWatchedFiles": {
                "dynamicRegistration": true,
                "relativePatternSupport": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "resolveSupport": {
                    "properties": [
                        "location.range"
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "workspaceFolders": true,
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            },
            "inlineValue": {
                "refreshSupport": true
            },
            "inlayHint": {
                "refreshSupport": true
            },
            "diagnostics": {
                "refreshSupport": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    },
                    "labelDetailsSupport": true
                },
                "insertTextMode": 2,
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                },
                "completionList": {
                    "itemDefaults": [
                        "commitCharacters",
                        "editRange",
                        "insertTextFormat",
                        "insertTextMode"
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": false
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true,
                "foldingRangeKind": {
                    "valueSet": [
                        "comment",
                        "imports",
                        "region"
                    ]
                },
                "foldingRange": {
                    "collapsedText": false
                }
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator",
                    "decorator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false,
                "serverCancelSupport": true,
                "augmentsSyntaxTokens": true
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            },
            "typeHierarchy": {
                "dynamicRegistration": true
            },
            "inlineValue": {
                "dynamicRegistration": true
            },
            "inlayHint": {
                "dynamicRegistration": true,
                "resolveSupport": {
                    "properties": [
                        "tooltip",
                        "textEdits",
                        "label.tooltip",
                        "label.location",
                        "label.command"
                    ]
                }
            },
            "diagnostic": {
                "dynamicRegistration": true,
                "relatedDocumentSupport": false
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "staleRequestSupport": {
                "cancel": true,
                "retryOnContentModified": [
                    "textDocument/semanticTokens/full",
                    "textDocument/semanticTokens/range",
                    "textDocument/semanticTokens/full/delta"
                ]
            },
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0"
            },
            "positionEncodings": [
                "utf-16"
            ]
        },
        "notebookDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "executionSummarySupport": true
            }
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///Users/crbelaus/Developer/hcmex",
            "name": "hcmex"
        }
    ]
}
```
</details>

The weirdest thing is that when I launch my local NextLS server and update my VSCode settings to:

```
  "elixir-tools.nextls.adapter": "tcp",
  "elixir-tools.nextls.port": 9000,
```

It seems to work just fine.

**Comment by mhanberg** [comment]
Just to confirm, you mean the new pre built binary?

What OS?

If you are on Mac, can you toggle your firewall on/off to see if it prompts you to let epmd/beam accept incoming connections.

**Comment by crbelaus** [comment]
I am currently using MacOS Ventura 13.4.1. I've disabled the firewall but doesn't seem to change anything.

**Comment by mhanberg** [comment]
can you ensure epmd is running by running `epmd -daemon` and then restart the editor?

also, can you try connecting via TCP, but by doing `~/.cache/elixir-tools/nextls/bin/nextls --port 9000` ?

**Comment by crbelaus** [comment]
I've just `rm -rf ~/.cache/elixir-tools` and restarted VSCode. I see the following information in the Extension Host log:

```
2023-08-16 15:28:55.964 [error] Error: Client is not running and can't be stopped. It's current state is: starting
	at _.shutdown (/Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:96701)
	at _.stop (/Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:96282)
	at _.stop (/Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:258296)
	at _.doInitialize (/Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:96105)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async _.start (/Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:92671)
2023-08-16 15:28:55.965 [error] Error: Cannot call write after a stream was destroyed
	at new NodeError (node:internal/errors:387:5)
	at _write (node:internal/streams/writable:323:11)
	at Writable.write (node:internal/streams/writable:336:10)
	at /Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:74611
	at new Promise (<anonymous>)
	at a.write (/Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:74529)
	at v.doWrite (/Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:62145)
	at /Users/crbelaus/.vscode/extensions/elixir-tools.elixir-tools-0.6.0/dist/extension.js:2:62040
```

When I manually launch `~/.cache/elixir-tools/nextls/bin/nextls --port 9000` the same problem persists.

**Comment by mhanberg** [comment]
What is the output of running `file ~/.cache/elixir-tools/nextls/bin/nextls` in the terminal?

**Comment by crbelaus** [comment]
This is the output:

```
file ~/.cache/elixir-tools/nextls/bin/nextls
/Users/crbelaus/.cache/elixir-tools/nextls/bin/nextls: Mach-O 64-bit executable arm64
```

When I manually launch the executable with `--stdio` it doesn't seem to do anything (although I am not sure if this is expected):

On the other hand, if I manually run the command specifying a port:

```
/Users/crbelaus/.cache/elixir-tools/nextls/bin/nextls --port 9000
```

And then configure VSCode to use TCP and that port, it connects just fine. But then I see this:

```
16:32:55.286 [error] Unable to load crypto library. Failed with error:
":load_failed, Failed to load NIF library: 'dlopen(/Users/crbelaus/Library/Application Support/.burrito/next_ls_erts-14.0.2_0.9.1/lib/crypto-5.2/priv/lib/crypto.so, 0x0002): Library not loaded: /opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib
  Referenced from: <2C226EF9-AC0A-3884-B271-1EBDA4BC8277> /Users/crbelaus/Library/Application Support/.burrito/next_ls_erts-14.0.2_0.9.1/lib/crypto-5.2/priv/lib/crypto.so
  Reason: tried: '/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/lib/libcrypto.1.1.dylib' (no such file), '/usr/lib/libcrypto.1.1.dylib' (no such file, not in dyld cache)'"
OpenSSL might not be installed on this system.


16:32:55.297 [warning] The on_load function for module crypto returned:
{:error,
 {:load_failed,
  ~c"Failed to load NIF library: 'dlopen(/Users/crbelaus/Library/Application Support/.burrito/next_ls_erts-14.0.2_0.9.1/lib/crypto-5.2/priv/lib/crypto.so, 0x0002): Library not loaded: /opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib\n  Referenced from: <2C226EF9-AC0A-3884-B271-1EBDA4BC8277> /Users/crbelaus/Library/Application Support/.burrito/next_ls_erts-14.0.2_0.9.1/lib/crypto-5.2/priv/lib/crypto.so\n  Reason: tried: '/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib' (no such file), '/usr/local/lib/libcrypto.1.1.dylib' (no such file), '/usr/lib/libcrypto.1.1.dylib' (no such file, not in dyld cache)'"}}


16:32:55.302 [error] LSP Exited.

Last message received: handle_notification %{"jsonrpc" => "2.0", "method" => "initialized", "params" => %{}}

** (UndefinedFunctionError) function :crypto.strong_rand_bytes/1 is undefined (module :crypto is not available)
    (crypto 5.2) :crypto.strong_rand_bytes(8)
    (next_ls 0.9.1) lib/next_ls.ex:631: NextLS.token/0
    (next_ls 0.9.1) lib/next_ls.ex:367: anonymous fn/3 in NextLS.handle_notification/2
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (next_ls 0.9.1) lib/next_ls.ex:366: NextLS.handle_notification/2
    (gen_lsp 0.5.0) lib/gen_lsp.ex:286: anonymous fn/4 in GenLSP.loop/3
    (gen_lsp 0.5.0) lib/gen_lsp.ex:309: GenLSP.attempt/3
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3




16:32:55.303 [error] LSP Exited.

Last message received: handle_request %{"id" => 0, "jsonrpc" => "2.0", "method" => "initialize", "params" => %{"capabilities" => %{"general" => %{"markdown" => %{"parser" => "marked", "version" => "1.1.0"}, "positionEncodings" => ["utf-16"], "regularExpressions" => %{"engine" => "ECMAScript", "version" => "ES2020"}, "staleRequestSupport" => %{"cancel" => true, "retryOnContentModified" => ["textDocument/semanticTokens/full", "textDocument/semanticTokens/range", "textDocument/semanticTokens/full/delta"]}}, "notebookDocument" => %{"synchronization" => %{"dynamicRegistration" => true, "executionSummarySupport" => true}}, "textDocument" => %{"callHierarchy" => %{"dynamicRegistration" => true}, "codeAction" => %{"codeActionLiteralSupport" => %{"codeActionKind" => %{"valueSet" => ["", "quickfix", "refactor", "refactor.extract", "refactor.inline", "refactor.rewrite", "source", "source.organizeImports"]}}, "dataSupport" => true, "disabledSupport" => true, "dynamicRegistration" => true, "honorsChangeAnnotations" => false, "isPreferredSupport" => true, "resolveSupport" => %{"properties" => ["edit"]}}, "codeLens" => %{"dynamicRegistration" => true}, "colorProvider" => %{"dynamicRegistration" => true}, "completion" => %{"completionItem" => %{"commitCharactersSupport" => true, "deprecatedSupport" => true, "documentationFormat" => ["markdown", "plaintext"], "insertReplaceSupport" => true, "insertTextModeSupport" => %{"valueSet" => [1, 2]}, "labelDetailsSupport" => true, "preselectSupport" => true, "resolveSupport" => %{"properties" => ["documentation", "detail", "additionalTextEdits"]}, "snippetSupport" => true, "tagSupport" => %{"valueSet" => [1]}}, "completionItemKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]}, "completionList" => %{"itemDefaults" => ["commitCharacters", "editRange", "insertTextFormat", "insertTextMode"]}, "contextSupport" => true, "dynamicRegistration" => true, "insertTextMode" => 2}, "declaration" => %{"dynamicRegistration" => true, "linkSupport" => true}, "definition" => %{"dynamicRegistration" => true, "linkSupport" => true}, "diagnostic" => %{"dynamicRegistration" => true, "relatedDocumentSupport" => false}, "documentHighlight" => %{"dynamicRegistration" => true}, "documentLink" => %{"dynamicRegistration" => true, "tooltipSupport" => true}, "documentSymbol" => %{"dynamicRegistration" => true, "hierarchicalDocumentSymbolSupport" => true, "labelSupport" => true, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]}, "tagSupport" => %{"valueSet" => [1]}}, "foldingRange" => %{"dynamicRegistration" => true, "foldingRange" => %{"collapsedText" => false}, "foldingRangeKind" => %{"valueSet" => ["comment", "imports", "region"]}, "lineFoldingOnly" => true, "rangeLimit" => 5000}, "formatting" => %{"dynamicRegistration" => true}, "hover" => %{"contentFormat" => ["markdown", "plaintext"], "dynamicRegistration" => true}, "implementation" => %{"dynamicRegistration" => true, "linkSupport" => true}, "inlayHint" => %{"dynamicRegistration" => true, "resolveSupport" => %{"properties" => ["tooltip", "textEdits", "label.tooltip", "label.location", "label.command"]}}, "inlineValue" => %{"dynamicRegistration" => true}, "linkedEditingRange" => %{"dynamicRegistration" => true}, "onTypeFormatting" => %{"dynamicRegistration" => true}, "publishDiagnostics" => %{"codeDescriptionSupport" => true, "dataSupport" => true, "relatedInformation" => true, "tagSupport" => %{"valueSet" => [1, 2]}, "versionSupport" => false}, "rangeFormatting" => %{"dynamicRegistration" => true}, "references" => %{"dynamicRegistration" => true}, "rename" => %{"dynamicRegistration" => true, "honorsChangeAnnotations" => true, "prepareSupport" => true, "prepareSupportDefaultBehavior" => 1}, "selectionRange" => %{"dynamicRegistration" => true}, "semanticTokens" => %{"augmentsSyntaxTokens" => true, "dynamicRegistration" => true, "formats" => ["relative"], "multilineTokenSupport" => false, "overlappingTokenSupport" => false, "requests" => %{"full" => %{"delta" => true}, "range" => true}, "serverCancelSupport" => true, "tokenModifiers" => ["declaration", "definition", "readonly", "static", "deprecated", "abstract", "async", "modification", "documentation", ...], "tokenTypes" => ["namespace", "type", "class", "enum", "interface", "struct", "typeParameter", "parameter", ...]}, "signatureHelp" => %{"contextSupport" => true, "dynamicRegistration" => true, "signatureInformation" => %{"activeParameterSupport" => true, "documentationFormat" => ["markdown", "plaintext"], "parameterInformation" => %{"labelOffsetSupport" => true}}}, "synchronization" => %{"didSave" => true, "dynamicRegistration" => true, "willSave" => true, "willSaveWaitUntil" => true}, "typeDefinition" => %{"dynamicRegistration" => true, "linkSupport" => true}, "typeHierarchy" => %{"dynamicRegistration" => true}}, "window" => %{"showDocument" => %{"support" => true}, "showMessage" => %{"messageActionItem" => %{"additionalPropertiesSupport" => true}}, "workDoneProgress" => true}, "workspace" => %{"applyEdit" => true, "codeLens" => %{"refreshSupport" => true}, "configuration" => true, "diagnostics" => %{"refreshSupport" => true}, "didChangeConfiguration" => %{"dynamicRegistration" => true}, "didChangeWatchedFiles" => %{"dynamicRegistration" => true, "relativePatternSupport" => true}, "executeCommand" => %{"dynamicRegistration" => true}, "fileOperations" => %{"didCreate" => true, "didDelete" => true, "didRename" => true, "dynamicRegistration" => true, "willCreate" => true, "willDelete" => true, "willRename" => true}, "inlayHint" => %{"refreshSupport" => true}, "inlineValue" => %{"refreshSupport" => true}, "semanticTokens" => %{"refreshSupport" => true}, "symbol" => %{"dynamicRegistration" => true, "resolveSupport" => %{"properties" => ["location.range"]}, "symbolKind" => %{"valueSet" => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, ...]}, "tagSupport" => %{"valueSet" => [1]}}, "workspaceEdit" => %{"changeAnnotationSupport" => %{"groupsOnLabel" => true}, "documentChanges" => true, "failureHandling" => "textOnlyTransactional", "normalizesLineEndings" => true, "resourceOperations" => ["create", "rename", "delete"]}, "workspaceFolders" => true}}, "clientInfo" => %{"name" => "Visual Studio Code", "version" => "1.81.1"}, "locale" => "en", "processId" => 12588, "rootPath" => "/Users/crbelaus/Developer/next-ls", "rootUri" => "file:///Users/crbelaus/Developer/next-ls", "trace" => "verbose", "workspaceFolders" => [%{"name" => "next-ls", "uri" => "file:///Users/crbelaus/Developer/next-ls"}]}}

** (UndefinedFunctionError) function :crypto.strong_rand_bytes/1 is undefined (module :crypto is not available)
    (crypto 5.2) :crypto.strong_rand_bytes(8)
    (next_ls 0.9.1) lib/next_ls.ex:631: NextLS.token/0
    (next_ls 0.9.1) lib/next_ls.ex:367: anonymous fn/3 in NextLS.handle_notification/2
    (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (next_ls 0.9.1) lib/next_ls.ex:366: NextLS.handle_notification/2
    (gen_lsp 0.5.0) lib/gen_lsp.ex:286: anonymous fn/4 in GenLSP.loop/3
    (gen_lsp 0.5.0) lib/gen_lsp.ex:309: GenLSP.attempt/3
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by crbelaus** [comment]
Hmm I now see that it complains that "OpenSSL might not be installed on this system.". Maybe the `--stdio` flag was somehow hiding those error messages.

If this is the problem maybe we need to move this to the NextLS repository instead. I do have OpenSSL 3.0 installed:

```
➜  ~ brew list | grep openssl
openssl@3
```

And when I start Elixir manually I do get the `:crypto` module without complaints:

```
➜  ~ iex
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Interactive Elixir (1.15.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :crypto.strong_rand_bytes 100
<<97, 141, 167, 78, 173, 192, 190, 80, 228, 135, 254, 32, 163, 99, 65, 97, 19,
  123, 22, 113, 131, 43, 252, 126, 70, 44, 42, 38, 198, 29, 111, 216, 61, 147,
  226, 81, 95, 208, 206, 37, 135, 99, 23, 135, 22, 121, 8, 130, 189, 50, ...>>
```

**Comment by crbelaus** [comment]
I've installed OpenSSL 1.1 and this seems to work now:

```
brew install openssl@1.1
```

Not sure if this is a requirement but, in that case, we should add it to the installation instructions.

**Comment by mhanberg** [comment]
does it work with --stdio and --port ?

**Comment by mhanberg** [comment]
Ahh, so since 25.1, OTP works with openssl 3.0, but prior to that you needed 1.1.

the pre-compiled ERTS runtimes that are downloaded when we build the executable must be linked to 1.1

**Comment by mhanberg** [comment]
Hmm, burrito is supposed to have openssl statically linked, so i'm confused as to why this was a problem

**Comment by doawoo** [comment]
Popping in to say that yes they should be static linked if the ERTS *came from the BEAM Machine* -- if the burrito app was built on a host machine that was the same configuration as the target machine it will utilize the local ERTS which could potentially be dynamically linked. 

Example:

If I am on a MacOS ARM machine and build for a MacOS ARM machine it would first grab my local ERTS which is probably dynamically linked...

This marks a small shortcoming in Burrito -- since it adds a variance to builds that may be unexpected. 

I can make a patch that forces it to always use BEAM Machine builds by default, ensuring that things are always linked statically.

**Comment by mhanberg** [comment]
Going to transfer and rename this issue as we have correctly identified the issue being a nextls item and not a vscode item
