### ISSUE TITLE
Unable to execute migrations after installation: `sqlite3 error: Database busy`

### ISSUE THREAD

**Issue by sylvester-roos** [elixir-tools/elixir-tools.vscode#62]
After the automatic download of NextLS it instantly fails to start the extension.

**OS**: NixOS 23.05
**vscode version**: VSCodium 1.78.2 (installed through home-manager with `programs.vscode.package = pkgs.vscodium.fhsWithPackages (ps: with ps; [ nil nixpkgs-fmt ]);`)

<details>
<summary>extension output</summary>

```
[NextLS] NextLS v0.13.4 has initialized!
[NextLS] Booting runtimes...
[NextLS] Beginning DB migration...
[Warn  - 11:37:12 AM] [NextLS] sqlite3 error: Database busy

statement: SELECT MAX(version) FROM schema;
arguments: []
[Error - 11:37:12 AM] LSP Exited.

Last message received: handle_notification %{"jsonrpc" => "2.0", "method" => "initialized", "params" => %{}}

** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, NextLS.DB, {%Protocol.UndefinedError{protocol: String.Chars, value: {:error, "Database busy"}, description: ""}, [{String.Chars, :impl_for!, 1, [file: ~c"lib/string/chars.ex", line: 3]}, {String.Chars, :to_string, 1, [file: ~c"lib/string/chars.ex", line: 22]}, {NextLS.DB.Schema, :init, 1, [file: ~c"lib/next_ls/db/schema.ex", line: 56]}, {NextLS.DB, :init, 1, [file: ~c"lib/next_ls/db.ex", line: 33]}, {:gen_server, :init_it, 2, [file: ~c"gen_server.erl", line: 962]}, {:gen_server, :init_it, 6, [file: ~c"gen_server.erl", line: 917]}, {:proc_lib, :init_p_do_apply, 3, [file: ~c"proc_lib.erl", line: 241]}]}}}}
    (next_ls 0.13.4) lib/next_ls.ex:571: anonymous fn/3 in NextLS.handle_notification/2
    (elixir 1.15.5) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
    (next_ls 0.13.4) lib/next_ls.ex:565: NextLS.handle_notification/2
    (gen_lsp 0.6.0) lib/gen_lsp.ex:285: anonymous fn/4 in GenLSP.loop/3
    (gen_lsp 0.6.0) lib/gen_lsp.ex:308: GenLSP.attempt/3
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3




11:37:12.388 [error] LSP Exited.
```
</details>

**Comment by sylvester-roos** [comment]
Update: restarting VSCodium fixes the issue. The migrations get executed and the extension seems to work as it should.

<details>
<summary>extension output</summary>

```
[NextLS] NextLS v0.13.4 has initialized!
[NextLS] Booting runtimes...
[NextLS] Beginning DB migration...
[Info  - 11:45:27 AM] [NextLS] Database is on the latest version: 5
[NextLS] Finished DB migration...
[NextLS] Using `elixir` found at: /nix/store/garmpnhik01qfxa45n39f3l8psnx3w68-elixir-1.14.5/bin/elixir
[NextLS] Connected to node nextls-runtime-1696585526943919785@odysseus
[NextLS] Runtime for folder xxx is ready...
[NextLS] Compiled xxx!
```
</details>

**Comment by mhanberg** [comment]
Glad you figured it out!

I'll makr this as closed, but i believe your first snippet showed an exception being raised from the logger, I'll get that fixed up.

Thanks!
