### ISSUE TITLE
Error trying to use on vscode Access Denied

### ISSUE THREAD

**Issue by newton-peixoto** [elixir-tools/elixir-tools.vscode#84]
Hello everyone

Any tips how to solve the following errors?

```[Error - 16:53:22] Client Next LS: connection to server is erroring.
write EPIPE
Shutting down server.
[Error - 16:53:22] Client Next LS: connection to server is erroring.
write EPIPE
[Error - 16:53:22] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at Dp.shutdown (/home/newton.neto/.vscode/extensions/elixir-tools.elixir-tools-0.14.1/dist/extension.js:52:8492)
	at Dp.stop (/home/newton.neto/.vscode/extensions/elixir-tools.elixir-tools-0.14.1/dist/extension.js:52:8071)
	at Dp.stop (/home/newton.neto/.vscode/extensions/elixir-tools.elixir-tools-0.14.1/dist/extension.js:55:37705)
	at Dp.handleConnectionError (/home/newton.neto/.vscode/extensions/elixir-tools.elixir-tools-0.14.1/dist/extension.js:54:63)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 16:53:22] Server initialization failed.
  Message: write EPIPE
  Code: -32099 
[Error - 16:53:22] Next LS client: couldn't create connection to server.
  Message: write EPIPE
  Code: -32099 
[Info  - 16:53:22] Connection to server got closed. Server will restart.
true
error: AccessDenied
```

trying to run it manually 

```
 ~ ~/.cache/elixir-tools/nextls/bin/nextls --port 9000
error: AccessDenied

```

**Comment by mhanberg** [comment]
Can you run the next LS uninstall command from the command palette and the restart? 

I've seen an error like this in dev but I can't remember exactly what it was from, but it was a packaging issue.

**Comment by mhanberg** [comment]
Can you also share your OS info and all that jazz

**Comment by newton-peixoto** [comment]
vscode version 
1.87.1
1e790d77f81672c49be070e04474901747115651
x64

Ubuntu 22.04

**Comment by newton-peixoto** [comment]
> Can you run the next LS uninstall command from the command palette and the restart?
> 
> I've seen an error like this in dev but I can't remember exactly what it was from, but it was a packaging issue.

Same error, unfourtunaly

**Comment by mhanberg** [comment]
Can you run the command you ran but with strace `strace path/to/nextls --port 9000`

**Comment by newton-peixoto** [comment]
```execve("/home/newton.neto/.cache/elixir-tools/nextls/bin/nextls", ["/home/newton.neto/.cache/elixir-"..., "--port", "9000"], 0x7ffca0a32570 /* 49 vars */) = 0
arch_prctl(ARCH_SET_FS, 0x121bf38)      = 0
set_tid_address(0x121bed0)              = 2095571
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
prlimit64(0, RLIMIT_STACK, {rlim_cur=16384*1024, rlim_max=RLIM64_INFINITY}, NULL) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x12160e7, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x1207dad}, NULL, 8) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe18cb1e000
openat(AT_FDCWD, "/tmp/libc-musl-17613ec13d9aa9e5e907e6750785c5bbed3ad49472ec12281f592e2f0f2d3dbd.so", O_RDWR|O_CREAT|O_TRUNC|O_LARGEFILE|O_CLOEXEC, 0666) = 3
fchmod(3, 0754)                         = 0
write(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\263\321\5\0\0\0\0\0"..., 752696) = 752696
close(3)                                = 0
mkdirat(AT_FDCWD, "/home/newton.neto/.local/share/.burrito", 0755) = -1 EEXIST (File exists)
mkdirat(AT_FDCWD, "/home/newton.neto/.local/share/.burrito/next_ls_erts-14.2.1_0.19.2", 0755) = -1 EEXIST (File exists)
faccessat(AT_FDCWD, "/home/newton.neto/.local/share/.burrito/next_ls_erts-14.2.1_0.19.2/_metadata.json", F_OK) = 0
openat(AT_FDCWD, "/home/newton.neto/.local/share/.burrito", O_RDONLY|O_LARGEFILE|O_CLOEXEC|O_DIRECTORY) = 3
mmap(0x7fe18cb1f000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe18cb1f000
openat(AT_FDCWD, "/home/newton.neto/.local/share/.burrito/next_ls_erts-14.2.1_0.19.2/_metadata.json", O_RDONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 4
mmap(0x7fe18cb20000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe18cb20000
read(4, "{\"options\":\"[reboot_system_after"..., 5249) = 476
read(4, "", 4773)                       = 0
close(4)                                = 0
lseek(3, 0, SEEK_SET)                   = 0
getdents64(3, 0x7fff4adb6308 /* 3 entries */, 1024) = 96
openat(AT_FDCWD, "/home/newton.neto/.local/share/.burrito/next_ls_erts-14.2.1_0.19.2/_metadata.json", O_RDONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 4
read(4, "{\"options\":\"[reboot_system_after"..., 5249) = 476
read(4, "", 4773)                       = 0
close(4)                                = 0
getdents64(3, 0x7fff4adb6308 /* 0 entries */, 1024) = 0
munmap(0x7fe18cb20000, 12288)           = 0
munmap(0x7fe18cb1f000, 4096)            = 0
mmap(0x7fe18cb23000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe18cb23000
ioctl(1, TIOCGWINSZ, {ws_row=55, ws_col=211, ws_xpixel=0, ws_ypixel=0}) = 0
mmap(0x7fe18cb26000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe18cb26000
openat(AT_FDCWD, "/home/newton.neto/.local/share/.burrito/next_ls_erts-14.2.1_0.19.2/releases/COOKIE", O_RDWR|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 4
read(4, "LMJBBFYNIMQ76MZJKSM3VNA53MGVGCYK"..., 1024) = 56
read(4, "", 968)                        = 0
mmap(0x7fe18cb27000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe18cb27000
mmap(0x7fe18cb2a000, 20480, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fe18cb2a000
execve("/home/newton.neto/.local/share/.burrito/next_ls_erts-14.2.1_0.19.2/erts-14.2.1/bin/erlexec", ["/home/newton.neto/.local/share/."..., "-elixir ansi_enabled true", "-noshell", "-s elixir start_cli", "-mode embedded", "-setcookie", "LMJBBFYNIMQ76MZJKSM3VNA53MGVGCYK"..., "-boot", "/home/newton.neto/.local/share/."..., "-boot_var", "RELEASE_LIB", "/home/newton.neto/.local/share/."..., "-args_file", "/home/newton.neto/.local/share/."..., "-config", "/home/newton.neto/.local/share/."..., "-extra", "--port", "9000"], 0x7fe18cb296b8 /* 54 vars */) = -1 EACCES (Permission denied)
write(2, "error: ", 7error: )                  = 7
write(2, "AccessDenied", 12AccessDenied)            = 12
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by mhanberg** [comment]
can you run `file /home/newton.neto/.local/share/.burrito/next_ls_erts-14.2.1_0.19.2/erts-14.2.1/bin/erlexec` and `ldd /home/newton.neto/.local/share/.burrito/next_ls_erts-14.2.1_0.19.2/erts-14.2.1/bin/erlexec`

**Comment by mhanberg** [comment]
also potentially uninstall nextls with `rm ~/.cache/elixir-tools/nextls/bin/nextls` and then `rm -rf /home/newton.neto/.local/share/.burrito/` and then reopening vscode to let it reinstall

part of me suspects that it somehow downloaded the wrong architecture or something

**Comment by mhanberg** [comment]
We have a hypothesis, might be related to your username having a `.` in it. 

I'll make a new user in my Linux computer with one and try it out. 

Not sure the fix if that's the case but we'll figure it out.
